### PR TITLE
Small fix to exportDbToSql() method

### PR DESCRIPTION
**Pull request by marqusG**
Prevent from adding CREATE and DROP statements for reserved tables in exportDbToSql() method.

### CODE REVIEW

**Comment by marqusG** [comment]
HI. I apologize but this is the first time I do a pull request and I really don't know the right way to go. I see you don't have merged my little fix yet and I wouldn't I have missed something important.
My fix is just the same you used to fix errors in exportDbToJson() preventing the code from trying to drop reserved tables, but applied to exportDbToSql() function.
Cheers
Marco

**Comment by dpa99c** [comment]
Thanks for this. Sorry it's taken a while - been busy.

**Comment by dpa99c** [comment]
Your fix is published to npm in `uk.co.workingedge.cordova.plugin.sqliteporter@1.0.1`

**Comment by marqusG** [comment]
No problem at all, Iwanted just to be sure to be in the right way with
Github conventions and rules :) Cheers



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=marqus.gs@gmail.com&idSignature=22>

**Pull request merged**
